# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annie', '0002_auto_20180421_0311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Introduction',
        ),
    ]
